parameters:
#    fcp_site.example.class: Fcp\SiteBundle\Example

services:
#    fcp_site.example:
#        class: %fcp_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
