<?php

namespace Proxies\__CG__\Fcp\SiteBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Player extends \Fcp\SiteBundle\Entity\Player implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setFirstName($firstName)
    {
        $this->__load();
        return parent::setFirstName($firstName);
    }

    public function getFirstName()
    {
        $this->__load();
        return parent::getFirstName();
    }

    public function setLastName($lastName)
    {
        $this->__load();
        return parent::setLastName($lastName);
    }

    public function getLastName()
    {
        $this->__load();
        return parent::getLastName();
    }

    public function setBirthday($birthday)
    {
        $this->__load();
        return parent::setBirthday($birthday);
    }

    public function getBirthday()
    {
        $this->__load();
        return parent::getBirthday();
    }

    public function setBioDescription($bioDescription)
    {
        $this->__load();
        return parent::setBioDescription($bioDescription);
    }

    public function getBioDescription()
    {
        $this->__load();
        return parent::getBioDescription();
    }

    public function setPreferredNumber($preferredNumber)
    {
        $this->__load();
        return parent::setPreferredNumber($preferredNumber);
    }

    public function getPreferredNumber()
    {
        $this->__load();
        return parent::getPreferredNumber();
    }

    public function setPreferredPosition($preferredPosition)
    {
        $this->__load();
        return parent::setPreferredPosition($preferredPosition);
    }

    public function getPreferredPosition()
    {
        $this->__load();
        return parent::getPreferredPosition();
    }

    public function setImagePath($imagePath)
    {
        $this->__load();
        return parent::setImagePath($imagePath);
    }

    public function getImagePath()
    {
        $this->__load();
        return parent::getImagePath();
    }

    public function setBoardFunction($boardFunction)
    {
        $this->__load();
        return parent::setBoardFunction($boardFunction);
    }

    public function getBoardFunction()
    {
        $this->__load();
        return parent::getBoardFunction();
    }

    public function setSlug($slug)
    {
        $this->__load();
        return parent::setSlug($slug);
    }

    public function getSlug()
    {
        $this->__load();
        return parent::getSlug();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'firstName', 'lastName', 'birthday', 'bioDescription', 'preferredNumber', 'preferredPosition', 'imagePath', 'boardFunction', 'slug');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}